name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn && yarn global add -g @lhci/cli
      - run: yarn build
      - run: npx lhci collect
      - run: npx lhci upload
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .lighthouseci/*.html
